// import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./ui/Navbar";
import { Poppins } from "next/font/google";
// import Footer from "./ui/Footer"

// const inter = Inter({ subsets: ["latin"] });

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['100', '300', '400', '500', '700', '900']
})
export const metadata = {
  title: "VitaloG",
  description: "Generated by create next app",
  imageUrl: "/vitalog.png",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
      <div className='flex flex-col justify-center max-w-[1440px] min-h-screen bg-bgLayout'>
        <Navbar/>
       <div>{children}</div>
 
        
        </div>
        
        </body>
    </html>
  );
}
